// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: llm_inference.proto

package llm_inference

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 输入文本
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferenceRequest) Reset() {
	*x = InferenceRequest{}
	mi := &file_llm_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceRequest) ProtoMessage() {}

func (x *InferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceRequest.ProtoReflect.Descriptor instead.
func (*InferenceRequest) Descriptor() ([]byte, []int) {
	return file_llm_inference_proto_rawDescGZIP(), []int{0}
}

func (x *InferenceRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *InferenceRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InferenceResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Chunk           string                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	IsFinished      bool                   `protobuf:"varint,2,opt,name=is_finished,json=isFinished,proto3" json:"is_finished,omitempty"`
	Error           string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	GeneratedTokens int32                  `protobuf:"varint,4,opt,name=generated_tokens,json=generatedTokens,proto3" json:"generated_tokens,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InferenceResponse) Reset() {
	*x = InferenceResponse{}
	mi := &file_llm_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceResponse) ProtoMessage() {}

func (x *InferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceResponse.ProtoReflect.Descriptor instead.
func (*InferenceResponse) Descriptor() ([]byte, []int) {
	return file_llm_inference_proto_rawDescGZIP(), []int{1}
}

func (x *InferenceResponse) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

func (x *InferenceResponse) GetIsFinished() bool {
	if x != nil {
		return x.IsFinished
	}
	return false
}

func (x *InferenceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *InferenceResponse) GetGeneratedTokens() int32 {
	if x != nil {
		return x.GeneratedTokens
	}
	return 0
}

var File_llm_inference_proto protoreflect.FileDescriptor

const file_llm_inference_proto_rawDesc = "" +
	"\n" +
	"\x13llm_inference.proto\x12\rllm_inference\"K\n" +
	"\x10InferenceRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8b\x01\n" +
	"\x11InferenceResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\tR\x05chunk\x12\x1f\n" +
	"\vis_finished\x18\x02 \x01(\bR\n" +
	"isFinished\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12)\n" +
	"\x10generated_tokens\x18\x04 \x01(\x05R\x0fgeneratedTokens2m\n" +
	"\x11InferencerService\x12X\n" +
	"\x0fStreamInference\x12\x1f.llm_inference.InferenceRequest\x1a .llm_inference.InferenceResponse(\x010\x01B\x1fZ\x1d./llm_inference;llm_inferenceb\x06proto3"

var (
	file_llm_inference_proto_rawDescOnce sync.Once
	file_llm_inference_proto_rawDescData []byte
)

func file_llm_inference_proto_rawDescGZIP() []byte {
	file_llm_inference_proto_rawDescOnce.Do(func() {
		file_llm_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llm_inference_proto_rawDesc), len(file_llm_inference_proto_rawDesc)))
	})
	return file_llm_inference_proto_rawDescData
}

var file_llm_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_llm_inference_proto_goTypes = []any{
	(*InferenceRequest)(nil),  // 0: llm_inference.InferenceRequest
	(*InferenceResponse)(nil), // 1: llm_inference.InferenceResponse
}
var file_llm_inference_proto_depIdxs = []int32{
	0, // 0: llm_inference.InferencerService.StreamInference:input_type -> llm_inference.InferenceRequest
	1, // 1: llm_inference.InferencerService.StreamInference:output_type -> llm_inference.InferenceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_llm_inference_proto_init() }
func file_llm_inference_proto_init() {
	if File_llm_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llm_inference_proto_rawDesc), len(file_llm_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llm_inference_proto_goTypes,
		DependencyIndexes: file_llm_inference_proto_depIdxs,
		MessageInfos:      file_llm_inference_proto_msgTypes,
	}.Build()
	File_llm_inference_proto = out.File
	file_llm_inference_proto_goTypes = nil
	file_llm_inference_proto_depIdxs = nil
}
