# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import contextengine_pb2 as contextengine__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in contextengine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ContextEngineServiceStub:
    """ContextEngineService builds optimized contexts for LLM inference.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BuildContext = channel.unary_unary(
                '/contextengine.ContextEngineService/BuildContext',
                request_serializer=contextengine__pb2.BuildContextRequest.SerializeToString,
                response_deserializer=contextengine__pb2.BuildContextResponse.FromString,
                _registered_method=True)


class ContextEngineServiceServicer:
    """ContextEngineService builds optimized contexts for LLM inference.
    """

    def BuildContext(self, request, context):
        """Build an optimized context under a token budget.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContextEngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BuildContext': grpc.unary_unary_rpc_method_handler(
                    servicer.BuildContext,
                    request_deserializer=contextengine__pb2.BuildContextRequest.FromString,
                    response_serializer=contextengine__pb2.BuildContextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'contextengine.ContextEngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('contextengine.ContextEngineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ContextEngineService:
    """ContextEngineService builds optimized contexts for LLM inference.
    """

    @staticmethod
    def BuildContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextengine.ContextEngineService/BuildContext',
            contextengine__pb2.BuildContextRequest.SerializeToString,
            contextengine__pb2.BuildContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
