# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contextengine.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'contextengine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63ontextengine.proto\x12\rcontextengine\"T\n\x13\x42uildContextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\x10\n\x08strategy\x18\x03 \x01(\t\x12\x0e\n\x06\x62udget\x18\x04 \x01(\x05\"d\n\x14\x42uildContextResponse\x12\x0f\n\x07\x63ontext\x18\x01 \x01(\t\x12\x10\n\x08strategy\x18\x02 \x01(\t\x12\x0e\n\x06tokens\x18\x03 \x01(\x05\x12\x19\n\x11\x63ompression_ratio\x18\x04 \x01(\x02\x32o\n\x14\x43ontextEngineService\x12W\n\x0c\x42uildContext\x12\".contextengine.BuildContextRequest\x1a#.contextengine.BuildContextResponseB\x1fZ\x1d./contextengine;contextengineb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contextengine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\035./contextengine;contextengine'
  _globals['_BUILDCONTEXTREQUEST']._serialized_start=38
  _globals['_BUILDCONTEXTREQUEST']._serialized_end=122
  _globals['_BUILDCONTEXTRESPONSE']._serialized_start=124
  _globals['_BUILDCONTEXTRESPONSE']._serialized_end=224
  _globals['_CONTEXTENGINESERVICE']._serialized_start=226
  _globals['_CONTEXTENGINESERVICE']._serialized_end=337
# @@protoc_insertion_point(module_scope)
