// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: contextengine.proto

package contextengine

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuildContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`         // Source text (conversation history / document)
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`       // Current query (for relevance strategies)
	Strategy      string                 `protobuf:"bytes,3,opt,name=strategy,proto3" json:"strategy,omitempty"` // truncation | project_topic | attention_sink | sink_topic | bm25_top1
	Budget        int32                  `protobuf:"varint,4,opt,name=budget,proto3" json:"budget,omitempty"`    // Token budget
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildContextRequest) Reset() {
	*x = BuildContextRequest{}
	mi := &file_contextengine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildContextRequest) ProtoMessage() {}

func (x *BuildContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contextengine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildContextRequest.ProtoReflect.Descriptor instead.
func (*BuildContextRequest) Descriptor() ([]byte, []int) {
	return file_contextengine_proto_rawDescGZIP(), []int{0}
}

func (x *BuildContextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *BuildContextRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *BuildContextRequest) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *BuildContextRequest) GetBudget() int32 {
	if x != nil {
		return x.Budget
	}
	return 0
}

type BuildContextResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Context          string                 `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`                                             // Optimized context
	Strategy         string                 `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"`                                           // Strategy used
	Tokens           int32                  `protobuf:"varint,3,opt,name=tokens,proto3" json:"tokens,omitempty"`                                              // Actual tokens in context
	CompressionRatio float32                `protobuf:"fixed32,4,opt,name=compression_ratio,json=compressionRatio,proto3" json:"compression_ratio,omitempty"` // 1 - used/full
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BuildContextResponse) Reset() {
	*x = BuildContextResponse{}
	mi := &file_contextengine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildContextResponse) ProtoMessage() {}

func (x *BuildContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contextengine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildContextResponse.ProtoReflect.Descriptor instead.
func (*BuildContextResponse) Descriptor() ([]byte, []int) {
	return file_contextengine_proto_rawDescGZIP(), []int{1}
}

func (x *BuildContextResponse) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *BuildContextResponse) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *BuildContextResponse) GetTokens() int32 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

func (x *BuildContextResponse) GetCompressionRatio() float32 {
	if x != nil {
		return x.CompressionRatio
	}
	return 0
}

var File_contextengine_proto protoreflect.FileDescriptor

const file_contextengine_proto_rawDesc = "" +
	"\n" +
	"\x13contextengine.proto\x12\rcontextengine\"s\n" +
	"\x13BuildContextRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x1a\n" +
	"\bstrategy\x18\x03 \x01(\tR\bstrategy\x12\x16\n" +
	"\x06budget\x18\x04 \x01(\x05R\x06budget\"\x91\x01\n" +
	"\x14BuildContextResponse\x12\x18\n" +
	"\acontext\x18\x01 \x01(\tR\acontext\x12\x1a\n" +
	"\bstrategy\x18\x02 \x01(\tR\bstrategy\x12\x16\n" +
	"\x06tokens\x18\x03 \x01(\x05R\x06tokens\x12+\n" +
	"\x11compression_ratio\x18\x04 \x01(\x02R\x10compressionRatio2o\n" +
	"\x14ContextEngineService\x12W\n" +
	"\fBuildContext\x12\".contextengine.BuildContextRequest\x1a#.contextengine.BuildContextResponseB\x1fZ\x1d./contextengine;contextengineb\x06proto3"

var (
	file_contextengine_proto_rawDescOnce sync.Once
	file_contextengine_proto_rawDescData []byte
)

func file_contextengine_proto_rawDescGZIP() []byte {
	file_contextengine_proto_rawDescOnce.Do(func() {
		file_contextengine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contextengine_proto_rawDesc), len(file_contextengine_proto_rawDesc)))
	})
	return file_contextengine_proto_rawDescData
}

var file_contextengine_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contextengine_proto_goTypes = []any{
	(*BuildContextRequest)(nil),  // 0: contextengine.BuildContextRequest
	(*BuildContextResponse)(nil), // 1: contextengine.BuildContextResponse
}
var file_contextengine_proto_depIdxs = []int32{
	0, // 0: contextengine.ContextEngineService.BuildContext:input_type -> contextengine.BuildContextRequest
	1, // 1: contextengine.ContextEngineService.BuildContext:output_type -> contextengine.BuildContextResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contextengine_proto_init() }
func file_contextengine_proto_init() {
	if File_contextengine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contextengine_proto_rawDesc), len(file_contextengine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contextengine_proto_goTypes,
		DependencyIndexes: file_contextengine_proto_depIdxs,
		MessageInfos:      file_contextengine_proto_msgTypes,
	}.Build()
	File_contextengine_proto = out.File
	file_contextengine_proto_goTypes = nil
	file_contextengine_proto_depIdxs = nil
}
