// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: contextengine.proto

package contextengine

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContextEngineService_BuildContext_FullMethodName = "/contextengine.ContextEngineService/BuildContext"
)

// ContextEngineServiceClient is the client API for ContextEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ContextEngineService builds optimized contexts for LLM inference.
type ContextEngineServiceClient interface {
	// Build an optimized context under a token budget.
	BuildContext(ctx context.Context, in *BuildContextRequest, opts ...grpc.CallOption) (*BuildContextResponse, error)
}

type contextEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContextEngineServiceClient(cc grpc.ClientConnInterface) ContextEngineServiceClient {
	return &contextEngineServiceClient{cc}
}

func (c *contextEngineServiceClient) BuildContext(ctx context.Context, in *BuildContextRequest, opts ...grpc.CallOption) (*BuildContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildContextResponse)
	err := c.cc.Invoke(ctx, ContextEngineService_BuildContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContextEngineServiceServer is the server API for ContextEngineService service.
// All implementations must embed UnimplementedContextEngineServiceServer
// for forward compatibility.
//
// ContextEngineService builds optimized contexts for LLM inference.
type ContextEngineServiceServer interface {
	// Build an optimized context under a token budget.
	BuildContext(context.Context, *BuildContextRequest) (*BuildContextResponse, error)
	mustEmbedUnimplementedContextEngineServiceServer()
}

// UnimplementedContextEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContextEngineServiceServer struct{}

func (UnimplementedContextEngineServiceServer) BuildContext(context.Context, *BuildContextRequest) (*BuildContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildContext not implemented")
}
func (UnimplementedContextEngineServiceServer) mustEmbedUnimplementedContextEngineServiceServer() {}
func (UnimplementedContextEngineServiceServer) testEmbeddedByValue()                              {}

// UnsafeContextEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContextEngineServiceServer will
// result in compilation errors.
type UnsafeContextEngineServiceServer interface {
	mustEmbedUnimplementedContextEngineServiceServer()
}

func RegisterContextEngineServiceServer(s grpc.ServiceRegistrar, srv ContextEngineServiceServer) {
	// If the following call panics, it indicates UnimplementedContextEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContextEngineService_ServiceDesc, srv)
}

func _ContextEngineService_BuildContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextEngineServiceServer).BuildContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContextEngineService_BuildContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextEngineServiceServer).BuildContext(ctx, req.(*BuildContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContextEngineService_ServiceDesc is the grpc.ServiceDesc for ContextEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContextEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "contextengine.ContextEngineService",
	HandlerType: (*ContextEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BuildContext",
			Handler:    _ContextEngineService_BuildContext_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contextengine.proto",
}
