// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: llm_inference.proto

package inference

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InferencerService_StreamInference_FullMethodName = "/inference.InferencerService/StreamInference"
)

// InferencerServiceClient is the client API for InferencerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InferencerServiceClient interface {
	StreamInference(ctx context.Context, in *InferenceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InferenceResponse], error)
}

type inferencerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInferencerServiceClient(cc grpc.ClientConnInterface) InferencerServiceClient {
	return &inferencerServiceClient{cc}
}

func (c *inferencerServiceClient) StreamInference(ctx context.Context, in *InferenceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InferenceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InferencerService_ServiceDesc.Streams[0], InferencerService_StreamInference_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InferenceRequest, InferenceResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InferencerService_StreamInferenceClient = grpc.ServerStreamingClient[InferenceResponse]

// InferencerServiceServer is the server API for InferencerService service.
// All implementations must embed UnimplementedInferencerServiceServer
// for forward compatibility.
type InferencerServiceServer interface {
	StreamInference(*InferenceRequest, grpc.ServerStreamingServer[InferenceResponse]) error
	mustEmbedUnimplementedInferencerServiceServer()
}

// UnimplementedInferencerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferencerServiceServer struct{}

func (UnimplementedInferencerServiceServer) StreamInference(*InferenceRequest, grpc.ServerStreamingServer[InferenceResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamInference not implemented")
}
func (UnimplementedInferencerServiceServer) mustEmbedUnimplementedInferencerServiceServer() {}
func (UnimplementedInferencerServiceServer) testEmbeddedByValue()                           {}

// UnsafeInferencerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferencerServiceServer will
// result in compilation errors.
type UnsafeInferencerServiceServer interface {
	mustEmbedUnimplementedInferencerServiceServer()
}

func RegisterInferencerServiceServer(s grpc.ServiceRegistrar, srv InferencerServiceServer) {
	// If the following call pancis, it indicates UnimplementedInferencerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InferencerService_ServiceDesc, srv)
}

func _InferencerService_StreamInference_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InferenceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InferencerServiceServer).StreamInference(m, &grpc.GenericServerStream[InferenceRequest, InferenceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InferencerService_StreamInferenceServer = grpc.ServerStreamingServer[InferenceResponse]

// InferencerService_ServiceDesc is the grpc.ServiceDesc for InferencerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InferencerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inference.InferencerService",
	HandlerType: (*InferencerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamInference",
			Handler:       _InferencerService_StreamInference_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "llm_inference.proto",
}
