# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from freechat.control.v1 import control_pb2 as freechat_dot_control_dot_v1_dot_control__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in freechat/control/v1/control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SchedulerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Route = channel.unary_unary(
                '/freechat.control.v1.SchedulerService/Route',
                request_serializer=freechat_dot_control_dot_v1_dot_control__pb2.RouteRequest.SerializeToString,
                response_deserializer=freechat_dot_control_dot_v1_dot_control__pb2.RouteDecision.FromString,
                _registered_method=True)
        self.RenewLease = channel.unary_unary(
                '/freechat.control.v1.SchedulerService/RenewLease',
                request_serializer=freechat_dot_control_dot_v1_dot_control__pb2.LeaseRequest.SerializeToString,
                response_deserializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.FromString,
                _registered_method=True)
        self.Release = channel.unary_unary(
                '/freechat.control.v1.SchedulerService/Release',
                request_serializer=freechat_dot_control_dot_v1_dot_control__pb2.LeaseRequest.SerializeToString,
                response_deserializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/freechat.control.v1.SchedulerService/Cancel',
                request_serializer=freechat_dot_control_dot_v1_dot_control__pb2.LeaseRequest.SerializeToString,
                response_deserializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.FromString,
                _registered_method=True)
        self.ExplainDecision = channel.unary_unary(
                '/freechat.control.v1.SchedulerService/ExplainDecision',
                request_serializer=freechat_dot_control_dot_v1_dot_control__pb2.LeaseRequest.SerializeToString,
                response_deserializer=freechat_dot_control_dot_v1_dot_control__pb2.RouteDecision.FromString,
                _registered_method=True)


class SchedulerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Route(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Release(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExplainDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Route': grpc.unary_unary_rpc_method_handler(
                    servicer.Route,
                    request_deserializer=freechat_dot_control_dot_v1_dot_control__pb2.RouteRequest.FromString,
                    response_serializer=freechat_dot_control_dot_v1_dot_control__pb2.RouteDecision.SerializeToString,
            ),
            'RenewLease': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewLease,
                    request_deserializer=freechat_dot_control_dot_v1_dot_control__pb2.LeaseRequest.FromString,
                    response_serializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.SerializeToString,
            ),
            'Release': grpc.unary_unary_rpc_method_handler(
                    servicer.Release,
                    request_deserializer=freechat_dot_control_dot_v1_dot_control__pb2.LeaseRequest.FromString,
                    response_serializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=freechat_dot_control_dot_v1_dot_control__pb2.LeaseRequest.FromString,
                    response_serializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.SerializeToString,
            ),
            'ExplainDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.ExplainDecision,
                    request_deserializer=freechat_dot_control_dot_v1_dot_control__pb2.LeaseRequest.FromString,
                    response_serializer=freechat_dot_control_dot_v1_dot_control__pb2.RouteDecision.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'freechat.control.v1.SchedulerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('freechat.control.v1.SchedulerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SchedulerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Route(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freechat.control.v1.SchedulerService/Route',
            freechat_dot_control_dot_v1_dot_control__pb2.RouteRequest.SerializeToString,
            freechat_dot_control_dot_v1_dot_control__pb2.RouteDecision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenewLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freechat.control.v1.SchedulerService/RenewLease',
            freechat_dot_control_dot_v1_dot_control__pb2.LeaseRequest.SerializeToString,
            freechat_dot_control_dot_v1_dot_control__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Release(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freechat.control.v1.SchedulerService/Release',
            freechat_dot_control_dot_v1_dot_control__pb2.LeaseRequest.SerializeToString,
            freechat_dot_control_dot_v1_dot_control__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freechat.control.v1.SchedulerService/Cancel',
            freechat_dot_control_dot_v1_dot_control__pb2.LeaseRequest.SerializeToString,
            freechat_dot_control_dot_v1_dot_control__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExplainDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freechat.control.v1.SchedulerService/ExplainDecision',
            freechat_dot_control_dot_v1_dot_control__pb2.LeaseRequest.SerializeToString,
            freechat_dot_control_dot_v1_dot_control__pb2.RouteDecision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerControlServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/freechat.control.v1.WorkerControlService/Register',
                request_serializer=freechat_dot_control_dot_v1_dot_control__pb2.WorkerRegistration.SerializeToString,
                response_deserializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.FromString,
                _registered_method=True)
        self.Heartbeat = channel.stream_stream(
                '/freechat.control.v1.WorkerControlService/Heartbeat',
                request_serializer=freechat_dot_control_dot_v1_dot_control__pb2.WorkerHeartbeat.SerializeToString,
                response_deserializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.FromString,
                _registered_method=True)
        self.Drain = channel.unary_unary(
                '/freechat.control.v1.WorkerControlService/Drain',
                request_serializer=freechat_dot_control_dot_v1_dot_control__pb2.WorkerRegistration.SerializeToString,
                response_deserializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.FromString,
                _registered_method=True)
        self.ApplyCacheAction = channel.unary_unary(
                '/freechat.control.v1.WorkerControlService/ApplyCacheAction',
                request_serializer=freechat_dot_control_dot_v1_dot_control__pb2.CacheActionRequest.SerializeToString,
                response_deserializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.FromString,
                _registered_method=True)


class WorkerControlServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Drain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyCacheAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=freechat_dot_control_dot_v1_dot_control__pb2.WorkerRegistration.FromString,
                    response_serializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.SerializeToString,
            ),
            'Heartbeat': grpc.stream_stream_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=freechat_dot_control_dot_v1_dot_control__pb2.WorkerHeartbeat.FromString,
                    response_serializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.SerializeToString,
            ),
            'Drain': grpc.unary_unary_rpc_method_handler(
                    servicer.Drain,
                    request_deserializer=freechat_dot_control_dot_v1_dot_control__pb2.WorkerRegistration.FromString,
                    response_serializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.SerializeToString,
            ),
            'ApplyCacheAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyCacheAction,
                    request_deserializer=freechat_dot_control_dot_v1_dot_control__pb2.CacheActionRequest.FromString,
                    response_serializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'freechat.control.v1.WorkerControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('freechat.control.v1.WorkerControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerControlService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freechat.control.v1.WorkerControlService/Register',
            freechat_dot_control_dot_v1_dot_control__pb2.WorkerRegistration.SerializeToString,
            freechat_dot_control_dot_v1_dot_control__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/freechat.control.v1.WorkerControlService/Heartbeat',
            freechat_dot_control_dot_v1_dot_control__pb2.WorkerHeartbeat.SerializeToString,
            freechat_dot_control_dot_v1_dot_control__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Drain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freechat.control.v1.WorkerControlService/Drain',
            freechat_dot_control_dot_v1_dot_control__pb2.WorkerRegistration.SerializeToString,
            freechat_dot_control_dot_v1_dot_control__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyCacheAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freechat.control.v1.WorkerControlService/ApplyCacheAction',
            freechat_dot_control_dot_v1_dot_control__pb2.CacheActionRequest.SerializeToString,
            freechat_dot_control_dot_v1_dot_control__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class KVControlServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportCacheEvents = channel.unary_unary(
                '/freechat.control.v1.KVControlService/ReportCacheEvents',
                request_serializer=freechat_dot_control_dot_v1_dot_control__pb2.CacheEventBatch.SerializeToString,
                response_deserializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.FromString,
                _registered_method=True)
        self.ApplyLifecycle = channel.unary_unary(
                '/freechat.control.v1.KVControlService/ApplyLifecycle',
                request_serializer=freechat_dot_control_dot_v1_dot_control__pb2.AgentHints.SerializeToString,
                response_deserializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.FromString,
                _registered_method=True)


class KVControlServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ReportCacheEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyLifecycle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KVControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportCacheEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportCacheEvents,
                    request_deserializer=freechat_dot_control_dot_v1_dot_control__pb2.CacheEventBatch.FromString,
                    response_serializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.SerializeToString,
            ),
            'ApplyLifecycle': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyLifecycle,
                    request_deserializer=freechat_dot_control_dot_v1_dot_control__pb2.AgentHints.FromString,
                    response_serializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'freechat.control.v1.KVControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('freechat.control.v1.KVControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KVControlService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReportCacheEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freechat.control.v1.KVControlService/ReportCacheEvents',
            freechat_dot_control_dot_v1_dot_control__pb2.CacheEventBatch.SerializeToString,
            freechat_dot_control_dot_v1_dot_control__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyLifecycle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freechat.control.v1.KVControlService/ApplyLifecycle',
            freechat_dot_control_dot_v1_dot_control__pb2.AgentHints.SerializeToString,
            freechat_dot_control_dot_v1_dot_control__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TraceReplayServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartReplay = channel.unary_unary(
                '/freechat.control.v1.TraceReplayService/StartReplay',
                request_serializer=freechat_dot_control_dot_v1_dot_control__pb2.ReplayRequest.SerializeToString,
                response_deserializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.FromString,
                _registered_method=True)
        self.StopReplay = channel.unary_unary(
                '/freechat.control.v1.TraceReplayService/StopReplay',
                request_serializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.SerializeToString,
                response_deserializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.FromString,
                _registered_method=True)
        self.GetReplayStatus = channel.unary_unary(
                '/freechat.control.v1.TraceReplayService/GetReplayStatus',
                request_serializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.SerializeToString,
                response_deserializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/freechat.control.v1.TraceReplayService/Health',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.FromString,
                _registered_method=True)


class TraceReplayServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StartReplay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopReplay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReplayStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TraceReplayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartReplay': grpc.unary_unary_rpc_method_handler(
                    servicer.StartReplay,
                    request_deserializer=freechat_dot_control_dot_v1_dot_control__pb2.ReplayRequest.FromString,
                    response_serializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.SerializeToString,
            ),
            'StopReplay': grpc.unary_unary_rpc_method_handler(
                    servicer.StopReplay,
                    request_deserializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.FromString,
                    response_serializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.SerializeToString,
            ),
            'GetReplayStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReplayStatus,
                    request_deserializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.FromString,
                    response_serializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=freechat_dot_control_dot_v1_dot_control__pb2.Operation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'freechat.control.v1.TraceReplayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('freechat.control.v1.TraceReplayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TraceReplayService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartReplay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freechat.control.v1.TraceReplayService/StartReplay',
            freechat_dot_control_dot_v1_dot_control__pb2.ReplayRequest.SerializeToString,
            freechat_dot_control_dot_v1_dot_control__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopReplay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freechat.control.v1.TraceReplayService/StopReplay',
            freechat_dot_control_dot_v1_dot_control__pb2.Operation.SerializeToString,
            freechat_dot_control_dot_v1_dot_control__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReplayStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freechat.control.v1.TraceReplayService/GetReplayStatus',
            freechat_dot_control_dot_v1_dot_control__pb2.Operation.SerializeToString,
            freechat_dot_control_dot_v1_dot_control__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freechat.control.v1.TraceReplayService/Health',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            freechat_dot_control_dot_v1_dot_control__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
